// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoTFG.Data;

#nullable disable

namespace ProyectoTFG.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20230601111112_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("ProyectoTFG.Data.Atendido", b =>
                {
                    b.Property<long>("TrabajadorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrabajadorId", "PacienteId");

                    b.ToTable("Atendido", (string)null);
                });

            modelBuilder.Entity("ProyectoTFG.Data.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdCita");

                    b.Property<int>("Duracion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("DATETIME");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PacienteID");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TrabajadorID");

                    b.HasKey("IdCita");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("ProyectoTFG.Data.Pacientes", b =>
                {
                    b.Property<int>("IdPac")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdPac");

                    b.Property<string>("PacApellido")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("pacApellido");

                    b.Property<string>("PacDireccion")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("pacDireccion");

                    b.Property<DateTime>("PacFechRegistro")
                        .HasColumnType("DATE")
                        .HasColumnName("pacFechRegistro");

                    b.Property<string>("PacGs")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("pacGS");

                    b.Property<string>("PacNombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("pacNombre");

                    b.Property<string>("PacSexo")
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("pacSexo");

                    b.HasKey("IdPac");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ProyectoTFG.Data.Trabajadores", b =>
                {
                    b.Property<int>("IdTrab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idtrab");

                    b.Property<string>("TrabApellido")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("trabApellido");

                    b.Property<string>("TrabCorreo")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("trabCorreo");

                    b.Property<string>("TrabDireccion")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("trabDireccion");

                    b.Property<DateTime>("TrabFechaContrato")
                        .HasColumnType("DATE")
                        .HasColumnName("trabFechaContrato");

                    b.Property<string>("TrabHorario")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("trabHorario");

                    b.Property<string>("TrabNombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("trabNombre");

                    b.Property<string>("TrabPuesto")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("trabPuesto");

                    b.Property<string>("TrabSexo")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("trabSexo");

                    b.Property<string>("TrabTel")
                        .HasColumnType("VARCHAR(15)")
                        .HasColumnName("trabTel");

                    b.HasKey("IdTrab")
                        .HasName("PrimaryKey_idtrab");

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("ProyectoTFG.Data.Usuario", b =>
                {
                    b.Property<int>("IdUsu")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IdUsu");

                    b.Property<string>("UsuNombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("usuNombre");

                    b.Property<string>("UsuPwd")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("usuPwd");

                    b.Property<string>("UsuRol")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("usuRol");

                    b.Property<int>("UsuTrabId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuTrabId");

                    b.HasKey("IdUsu");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
